
NETWORK = "192.168.33"
lastoctet = 200

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "#{NETWORK}.#{lastoctet}"
  end

  (1..2).each do |i|
    config.vm.define "node-#{i}" do |master|
      master.vm.hostname = "node-#{i}"
      master.vm.network "private_network", ip: "#{NETWORK}.#{lastoctet+i}"
    end
  end
end
